all	:
	gcc -o pthread_test pthread_test.c -lpthread
	./pthread_test
mutex	:
	gcc -o mutex mutex.c -lpthread
	./mutex
sem	:
	gcc -o sem sem.c -lpthread
	./sem
procon	:
	gcc -o mutex mutex.c -lpthread
	./mutex
C	:
	gcc -o C C.c -lpthread
	./C
S	:
	gcc -o S S.c -lpthread
	./S
admin	:
	gcc -o admin admin.c -lpthread
	gcc -o procon procon.c -lpthread	
